// Static field definitions per container, derived from SQL export queries.
// field(id, search, match, show) — search:true means it appears in the search form by default.
// logic: 'or' means this condition is OR'd with the previous one (can be toggled to 'and').
// expr: optional Cosmos SQL expression override (used for computed/derived fields).

const field = (id, search = false, match = '=', show = true) => ({
  id, show, search, match, logic: 'or', value: ''
})
const sw = (id) => field(id, true, '=%') // starts-with, search on by default

// PageCount is a virtual field — it searches ARRAY_LENGTH(c["Pages"]) in Cosmos.
// show is false because the count is always rendered client-side from Pages.length.
const pageCount = () => ({
  id: 'PageCount', show: false, search: false, match: 'i>=', logic: 'or', value: '',
  expr: 'ARRAY_LENGTH(c["Pages"])',
})

export default {
  app_billing: [
    field('id', false, '=%', false),
    sw('IndexDate'),
    field('Doc_Type'),
    field('BOLNumber'),
    field('OrderNumber'),
    field('AccountID'),
    field('Product'),
    field('GrossVolume'),
    field('NetVolume'),
    field('ShipperCity'),
    field('ShipperState'),
    field('ConsigneeCity'),
    field('ConsigneeState'),
    field('StartDate'),
    field('Terminal'),
    field('BillToCode'),
    field('InvoiceNumber'),
    field('InvoiceDate'),
    field('TractorNumber'),
    field('TrailerNumber'),
    field('DriverCode'),
    field('ShipperCode'),
    field('ConsigneeCode'),
    field('RefNumber'),
    pageCount(),
  ],
  app_ar: [
    field('id', false, '=%', false),
    sw('IndexDate'),
    field('Doc_Type'),
    field('CheckNumber'),
    field('BatchName'),
    field('TotalAmount'),
    field('TransactionNumber'),
    field('TransactionTotal'),
    field('ConfirmationNumber'),
    field('Customer'),
    field('CheckDate'),
    field('SubmissionDate'),
    field('EffectiveDate'),
    pageCount(),
  ],
  app_ap: [
    field('id', false, '=%', false),
    sw('IndexDate'),
    field('InvoiceNumber'),
    field('InvoiceAmount'),
    field('InvoiceDate'),
    field('VendorID'),
    field('VendorName'),
    field('VoucherNumber'),
    field('PONumber'),
    field('Terms'),
    field('CompanyCode'),
    field('AccountCode'),
    field('TerminalNumber'),
    field('Location'),
    field('PostingDate'),
    pageCount(),
  ],
  app_ds: [
    field('id', false, '=%', false),
    sw('IndexDate'),
    field('Doc_Type'),
    field('DriverCode'),
    field('DriverName'),
    field('RunDate'),
    field('TerminalCode'),
    field('FromDate'),
    field('SettlementType'),
    field('ToDate'),
    pageCount(),
  ],
  app_driver: [
    field('id', false, '=%', false),
    sw('IndexDate'),
    field('Doc_Type'),
    field('ShipsID', false, '=', false),
    field('SSN', false, '=', false),
    field('FirstName'),
    field('MiddleName'),
    field('LastName'),
    field('PreviousEmployer'),
    field('ExpirationDate'),
    field('DriverCode'),
    field('TractorNumber'),
    field('VIN'),
    field('FleetShipsID'),
    field('Endorsements'),
    field('HazEndorseExpiration'),
    field('DoubTripEndorseExpiration'),
    field('PassEndorseExpiration'),
    field('TankEndorseExpiration'),
    field('TankHazEndorsementExpiration'),
    field('DriverID'),
    field('AccidentNumber'),
    field('AccidentDate'),
    field('ADCompany'),
    field('DABatchID', false, '=', false),
    field('LicenseState'),
    pageCount(),
  ],
}
